name: portfolio_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get:
  google_fonts: ^6.2.1
  font_awesome_flutter: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
